version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev
    container_name: app
    env_file:
      - ./.env
    depends_on:
      - postgresql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
  
  postgresql:
    container_name: postgresql
    image: postgres:latest
    restart: always
    volumes:
      - ./sql/mock.sql:/docker-entrypoint-initdb.d/mock.sql
    env_file:
      - ./docker.env
    ports:
      - '5432:5432'